### ISSUE TITLE
spring-cloud-services-starter-circuit-breaker 2.3.0 depends on a SNAPSHOT

### ISSUE THREAD

**Issue by snicoll** [pivotal-cf/spring-cloud-services-starters#194]
Following the upgrade on start.spring.io, our metadata verification started to fail:

```
java.lang.RuntimeException: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at io.pivotal.spring.cloud:spring-cloud-services-starter-circuit-breaker:pom:2.3.0.RELEASE -> org.springframework.cloud:spring-cloud-starter-stream-rabbit:jar:3.0.13.BUILD-SNAPSHOT
	at io.spring.start.site.MetadataVerificationTests.collectDependencies(MetadataVerificationTests.java:92)
	at io.spring.start.site.MetadataVerificationTests.dependencyStarterConfigurationIsCorrect(MetadataVerificationTests.java:78)
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at io.pivotal.spring.cloud:spring-cloud-services-starter-circuit-breaker:pom:2.3.0.RELEASE -> org.springframework.cloud:spring-cloud-starter-stream-rabbit:jar:3.0.13.BUILD-SNAPSHOT
	at io.spring.start.site.MetadataVerificationTests.collectDependencies(MetadataVerificationTests.java:92)
	at io.spring.start.site.MetadataVerificationTests.dependencyStarterConfigurationIsCorrect(MetadataVerificationTests.java:78)
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at io.pivotal.spring.cloud:spring-cloud-services-starter-circuit-breaker:pom:2.3.0.RELEASE -> org.springframework.cloud:spring-cloud-starter-stream-rabbit:jar:3.0.13.BUILD-SNAPSHOT
	at io.spring.start.site.MetadataVerificationTests.collectDependencies(MetadataVerificationTests.java:92)
	at io.spring.start.site.MetadataVerificationTests.dependencyStarterConfigurationIsCorrect(MetadataVerificationTests.java:78)
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.springframework.cloud:spring-cloud-starter-stream-rabbit:jar:3.0.13.BUILD-SNAPSHOT
	at io.spring.start.site.MetadataVerificationTests.collectDependencies(MetadataVerificationTests.java:92)
	at io.spring.start.site.MetadataVerificationTests.dependencyStarterConfigurationIsCorrect(MetadataVerificationTests.java:78)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.springframework.cloud:spring-cloud-starter-stream-rabbit:pom:3.0.13.BUILD-SNAPSHOT in central (https://repo1.maven.org/maven2)
	at io.spring.start.site.MetadataVerificationTests.collectDependencies(MetadataVerificationTests.java:92)
	at io.spring.start.site.MetadataVerificationTests.dependencyStarterConfigurationIsCorrect(MetadataVerificationTests.java:78)
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.springframework.cloud:spring-cloud-starter-stream-rabbit:pom:3.0.13.BUILD-SNAPSHOT in central (https://repo1.maven.org/maven2)
	at io.spring.start.site.MetadataVerificationTests.collectDependencies(MetadataVerificationTests.java:92)
	at io.spring.start.site.MetadataVerificationTests.dependencyStarterConfigurationIsCorrect(MetadataVerificationTests.java:78)
```

**Comment by snicoll** [comment]
A minute after submitting this, I've realized that this actually quite an old release. I wonder where that reference comes from. I didn't find a module for this starter, is it the right issue tracker to investigate this?

**Comment by snicoll** [comment]
It's likely to be a fluke in Aether resolution as we haven't experienced this again.
